#:import MDIContainer ui.mdi.mdi_container.MDIContainer
#:include ui/mdi/mdi_container.kv
#:import TilingWindowManager ui.mdi.window_manager.TilingWindowManager
#:import FloatingWindowManager ui.mdi.window_manager.FloatingWindowManager
#:import TilingOrientation ui.mdi.window_manager.tiling.TilingOrientation


<TilingOrientationSwitcher>:
    text: "Вертикаль" if self.is_down else "Горизонталь"
    size_hint: (None, 1)
    width: "128dp"
    on_is_down: self.mdi_manager.workspace_now.layout_mode.tiling_orientation = TilingOrientation.VERTICAL if self.is_down else TilingOrientation.HORIZONTAL
    is_down: not ((isinstance(self.mdi_manager.workspace_now.layout_mode, TilingWindowManager) and self.mdi_manager.workspace_now.layout_mode.tiling_orientation) is TilingOrientation.HORIZONTAL)


<WindowManagerSwitcher>:
    text: "Tiling" if self.is_down else "Floating"
    size_hint: (None, 1)
    width: "128dp"
    on_is_down: self.mdi_manager.workspace_now.window_manager = TilingWindowManager if self.is_down else FloatingWindowManager
    is_down: self.mdi_manager.workspace_now.window_manager is not FloatingWindowManager


<MDIContainerManager>:  # WorskpaceManager
    workspace_cls: MDIContainer
