#:import DesktopMap ui.mdi.desktops.desktop_map.DesktopMap


<MapFreezeToggleDesktop>:  # HoverToggleButton
    text: "Заморожено" if self.is_down else "Заморозить"
    size_hint: (None, 1)
    width: "128dp"


<DesktopMapSection>:  # SectionPanel
    workspace_manager: workspace_manager

    size_hint: (1, 1)
    title_text: "Рабочий стол #{}".format(workspace_manager.workspace_now_index + 1 if workspace_manager.workspace_now_index else 1)
    WorkspaceManager:
        id: workspace_manager
        workspace_cls: DesktopMap
