#:import PlayerStatus misc.player.status.PlayerStatus


<DesktopRotaryUix>:  # DesktopUix
    design_grid_size: [6, 11]
    grid_size: [5, 9]

    bg_image: imgs_path.button_thumb_normal
    HoverInput:
        id: title_input
        size_hint: [0.875, 0.125]
        pos_hint: {"x": 0.0625, "y": 0.824}
        font_size: "11sp"
        multiline: False
        text: root.desktop_uix.title
        on_text: root.desktop_uix.edit(title=self.text)
    NumericInput:
        size_hint: [0.65625, 0.125]
        pos_hint: {"x": 0.167, "y": 0.642}
        minimum: root.desktop_uix.value_1_minimum
        maximum: root.desktop_uix.value_1_maximum
        value: root.desktop_uix._value_1
        on_value: root.desktop_uix.edit(value_1=self.value)
        disabled: root.desktop_uix.player.status is PlayerStatus.RELEASE or root.desktop_uix.player.status is PlayerStatus.ATTACK
    RotaryButton:
        size_hint: [0.65625, 0.358]
        pos_hint: {"x": 0.167, "y": 0.273}
        minimum: root.desktop_uix.value_1_minimum
        maximum: root.desktop_uix.value_1_maximum
        value: root.desktop_uix._value_1
        on_value: root.desktop_uix.edit(value_1=self.value)
        disabled: root.desktop_uix.player.status is PlayerStatus.RELEASE or root.desktop_uix.player.status is PlayerStatus.ATTACK
    HotkeyInput:
        size_hint: [0.26, 0.142]
        pos_hint: {"x": 0.21875, "y": 0.0852}
        font_size: "12sp"
        text: root.desktop_uix.player.hotkey
        on_text: root.desktop_uix.player.edit(hotkey=self.text)
    MomentToggleButton:
        size_hint: [0.26, 0.142]
        pos_hint: {"x": 0.53125, "y": 0.085}
        is_moment: root.desktop_uix.player.is_moment
        is_down: root.desktop_uix.active
        on_is_down: root.desktop_uix.edit(active=self.is_down)
        disabled: not root.desktop_uix.link_active or (root.desktop_uix.player.status is PlayerStatus.RELEASE)
