#:import PlayerStatus misc.player.status.PlayerStatus


<DesktopSlider2D>:  # DesktopUix
    grid_size: [9, 12]
    bg_image: imgs_path.slider2d_bg_thumb

    HoverInput:
        id: title_input
        size_hint: [0.9318, 0.086]
        pos_hint: {"x": 0.0341, "y": 0.879}
        text: root.desktop_uix.title
        font_size: 11
        multiline: False
        on_text: root.desktop_uix.edit(title=self.text)

    Slider2D:
        padding: 7
        size_hint: [0.915, 0.629]
        pos_hint: {"x": 0.034, "y": 0.226}

        value_x: root.desktop_uix._value_1
        value_y: root.desktop_uix._value_2

        value_x_minimum: root.desktop_uix.value_1_minimum
        value_x_maximum: root.desktop_uix.value_1_maximum

        value_y_minimum: root.desktop_uix.value_2_minimum
        value_y_maximum: root.desktop_uix.value_2_maximum

        on_value_x: root.desktop_uix.value_1 = self.value_x
        on_value_y: root.desktop_uix.value_2 = self.value_y

        disabled: root.desktop_uix.player.status is PlayerStatus.RELEASE or root.desktop_uix.player.status is PlayerStatus.ATTACK

    SubSectionPanel:
        title_text: "-" if root.desktop_uix.fixture_param_1 is None else root.desktop_uix.fixture_param_1.title
        font_size: 10
        halign: "center"
        padding: 0
        size_hint: [0.267, 0.148]
        pos_hint: {"x": 0.045, "y": 0.051}
        NumericInput:
            size_hint: (1, 1)
            minimum: root.desktop_uix.value_1_minimum
            maximum: root.desktop_uix.value_1_maximum
            value: root.desktop_uix._value_1
            on_value: root.desktop_uix.value_1 = self.value
    SubSectionPanel:
        title_text: "-" if root.desktop_uix.fixture_param_2 is None else root.desktop_uix.fixture_param_2.title
        size_hint: [0.267, 0.148]
        pos_hint: {"x": 0.341, "y": 0.051}
        font_size: 10
        halign: "center"
        padding: 0
        NumericInput:
            size_hint: (1, 1)
            minimum: root.desktop_uix.value_2_minimum
            maximum: root.desktop_uix.value_2_maximum
            value: root.desktop_uix._value_2
            on_value: root.desktop_uix.value_2 = self.value

    HotkeyInput:
        font_size: 12
        text: root.desktop_uix.player.hotkey
        on_text: root.desktop_uix.player.edit(hotkey=self.text)
        size_hint: [0.142, 0.098]
        pos_hint: {"x": 0.64, "y": 0.078}
    MomentToggleButton:
        is_moment: root.desktop_uix.player.is_moment
        is_down: root.desktop_uix.active
        on_is_down: root.desktop_uix.edit(active=self.is_down)
        disabled: not root.desktop_uix.link_active or (root.desktop_uix.player.status is PlayerStatus.RELEASE)
        size_hint: [0.142, 0.097]
        pos_hint: {"x": 0.795, "y": 0.078}
