import sys
from pathlib import Path

# misc
APP_NAME = "U-DMX Контроллер"
VERSION = "0.01"
SUB_VERSION = "Alpha"
PROFILING_CPU = False
PROFILING_RAM = False
DEBUG = False

BACKUP_MENU_ENV_KEY = "EXEC_BACKUP_MENU"
BACKUP_MENU_ENV_KEY_TRUE = "True"
BACKUP_MENU_ENV_KEY_FALSE = "False"
SESSION_LOG_ENV_KEY = "SESSION_LOG_FILEPATH"

BYTE_ORDER = "little"

# Определяем директорию, где находится скрипт или исполняемый файл
if getattr(sys, "frozen", False):
    # Для Nuitka или PyInstaller
    SCRIPT_DIR = Path(sys.executable).parent.parent
else:
    # Для обычного Python-скрипта
    SCRIPT_DIR = Path(__file__).parent.parent

# Создаём путь к папке database_data
DATABASE_PATH = SCRIPT_DIR / "database_data"
DATABASE_BACKUPS_PATH = SCRIPT_DIR / "database_backup"
DATABASE_BACKUPS_ARCHIVE_FORMAT = "gztar"
DATABASE_BACKUPS_ARCHIVE_EXTENSION = ".tar.gz"

DATABASE_MDI_WORKSPACES_COUNT = 9

PRESETS_PATH = SCRIPT_DIR / "presets_data"
PRESETS_FIXTURE_SUBDIR = "fixtures"
PRESETS_FIXTURES_PATH = PRESETS_PATH / PRESETS_FIXTURE_SUBDIR
PRESETS_PARAMS_SUBDIR = "params"
PRESETS_PARAMS_PATH = PRESETS_PATH / PRESETS_PARAMS_SUBDIR

FIXTURE_TEMP_DEPENDENCE_DEFAULT = 0
FIXTURE_TEMP_DEPENDENCE_MIN = 0
FIXTURE_TEMP_DEPENDENCE_MAX = 3000

FIXTURE_GROUP_REPEAT_COUNT_MIN = 1
FIXTURE_GROUP_REPEAT_COUNT_MAX = 64

BEATS_COUNT_MINIMIUM = 1
BEATS_COUNT_MAXIMUM = 16
FRAMES_IN_BEAT = 30
FRAMES_IN_HALFBEAT = FRAMES_IN_BEAT // 2
FRAMES_MAXIMUM = BEATS_COUNT_MAXIMUM * FRAMES_IN_BEAT

TEMP_MINIMUM = 1
TEMP_MAXIMUM = 300

DIMMER_MINIMUM = 0
DIMMER_MAXIMUM = 100

FADE_TO_BLACK_MS_MINIMUM = 0
FADE_TO_BLACK_MS_MAXIMUM = 3000

DENSITY_MINIMUM = 0.5
DENSITY_MAXIMUM = 2.0


# data paths
IMGS_PATH = SCRIPT_DIR / "data/imgs"
CURSOR_PATH = IMGS_PATH / "cursors"
FIXTURE_IMGS_PATH = SCRIPT_DIR / "data/fixtures"
DEFAULT_FIXTURE_ICON = FIXTURE_IMGS_PATH / "none.png"
FONTS_PATH = SCRIPT_DIR / "data/fonts"


# logs
LOGS_PATH = SCRIPT_DIR / "logs"
MAX_LOG_FILES = 10


# event thread
EVENT_THREAD_FPS = 120


# UI
MAP_LAYOUT_GRID_SIZE = 16
MAP_LAYOUT_MAX_SIZE = 128
MAP_LAYOUT_MAX_SIZE_PX = MAP_LAYOUT_GRID_SIZE * MAP_LAYOUT_MAX_SIZE

# dmx
DMX_UNIVERSE_COUNT = 32
DMX_ADDRESS_COUNT = 512

SERIAL_BAUDRATE = 115200
SERIAL_TIMEOUT = 1
SERIAL_MONITORING_CALL_INTERVAL = 1/3
DMX_WRITE_INTERVAL = 1/60
DMX_MESSAGE_BYTEORDER = "little"

DMX_LIGHT_FPS = 45

DMX_KEY_FRAME_TIME = 0.25
DMX_HELLO_MSG = b"SAMPO"

SERIAL_TRY_CONNECTION_TIME = 10.0


# midi

MIDI_MONITORING_CALL_INTERVAL = 1/3
MIDI_MAXIMUM_CHANNEL = 128
