<BasePatchUiPanButton>:  # HoverToggleButton
    text: "П"
    size_hint: (0.25, 0.146)
    pos_hint: {"x": 0.75, "y": 0.854}
    is_down: self.patch_ui.patch.invert_pan
    on_is_down: self.patch_ui.patch.edit(invert_pan=self.is_down)


<BasePatchUiTiltButton>:  # HoverToggleButton
    text: "Т"
    size_hint: (0.25, 0.146)
    pos_hint: {"x": 0.75, "y": 0.708}
    is_down: self.patch_ui.patch.invert_tilt
    on_is_down: self.patch_ui.patch.edit(invert_tilt=self.is_down)


<BasePatchUi>:  # RelativeLayout
    input_start_address: input_start_address.__self__
    input_universe: input_universe.__self__
    toggle_controller: toggle_controller.__self__
    lbl_addr_info: lbl_addr_info.__self__
    image_fixture: image_fixture.__self__
    input_title: input_title.__self__
    toggle_mapper: toggle_mapper.__self__

    size_hint: (None, None)
    grid_size: [5, 5]
    canvas.before:
        Color:
            rgba: self.bg
        Rectangle:
            pos: (0, 0)
            size: self.size
    NumericInput:
        id: input_start_address
        pos_hint: {"x": 0, "y": 0.78}
        size_hint: [0.25, 0.22]
        minimum: 1
        maximum: constants.DMX_ADDRESS_COUNT
        value: root.patch.start_address
        on_value: root.patch.edit(start_address=self.value)
    NumericInput:
        id: input_universe
        pos_hint: {"x": 0, "y": 0.56}
        size_hint: [0.25, 0.22]
        minimum: 1
        maximum: constants.DMX_UNIVERSE_COUNT
        value: root.patch.universe
        on_value: root.patch.edit(universe=self.value)
    HoverToggleButton:
        id: toggle_controller
        pos_hint: {"x": 0.0, "y": 0.375}
        size_hint: (0.25, 0.18)
        text: "c"
        font_size: "13sp"
        on_press: root.open_controller_menu()
    RestrictedLabel:
        id: lbl_addr_info
        size_hint: (None, None)
        text: "{}: {}-{}".format(root.patch.universe, root.patch.start_address, root.patch.end_address)
        font_size: "9sp"
        size: self.texture_size
        text_size: (None, None)
        pos: ("{}dp".format((root.width - self.size[0]) // 2), "{}dp".format(root.height - self.size[1]))
        color: cs.PatchUi.addr_info_addr_conflict if root.patch.is_address_conflict else cs.PatchUi.addr_info_normal
    Image:
        id: image_fixture
        size_hint: (0.52, 0.52)
        pos: ("{}dp".format((root.width - self.size[0]) // 2), "{}dp".format(root.height - self.size[1] - 10))
        source: (constants.FIXTURE_IMGS_PATH / root.patch.fixture.icon).as_posix()
    HoverInput:
        id: input_title
        pos_hint: {"x": 0, "y": 0.146}
        size_hint: (1, 0.25)
        multiline: False
        text: root.patch.title
        on_text: root.patch.edit(title=self.text)
    HoverToggleButton:
        id: toggle_mapper
        pos_hint: {"x": 0.75, "y": 0.376}
        size_hint: (0.25, 0.18)
        text: "m"
        font_size: "13sp"
        on_press: root.open_mapper_menu()
