<TableHeaderToggle>:  # ArrowToggleButton
    text: self.column_config.header_text
    size_hint_x: self.column_config.size_hint_x
    disabled: self.column_config.sorting_block
    reverse_arrow: self.sorting_reverse
    do_show_arrow: self.sorting_active
    arrow_offset_right: "8dp"
    is_down: self.sorting_active
    on_is_down: self.is_down = self.sorting_active


<DatabaseTableHeader>:  # BoxLayout
    size_hint: (1, None)
    height: "30dp"
    spacing: "2dp"


<DatabaseTableRow>:  # BoxLayout
    size_hint: (1, None)
    height: "80dp"
    spacing: "2dp"


<DatabaseTableUi>:  # BoxLayout
    header: header
    scroll_layout: scroll_layout

    spacing: "2dp"
    orientation: "vertical"
    canvas.before:
        Color:
            rgba: cs.DatabaseTable.bg
        Rectangle:
            pos: self.pos
            size: self.size

    DatabaseTableHeader:
        id: header
        padding: [0, 0, "{}dp".format(scroll_layout.scrollbar_vertical.width if scroll_layout.scrollbar_vertical else 0), 0]
    ScrollLayout:
        id: scroll_layout
        scrollview: scrollview
        RecycleRestrictedScrollView:
            id: scrollview
            viewclass: "DatabaseTableRow"
            scroll_by_content: True
            do_scroll_x: False
            do_scroll_by_element: True
            RecycleBoxLayout:
                size_hint: (1, None)
                spacing: "2dp"
                orientation: "vertical"
                default_size_hint: (1, None)
                height: self.minimum_height
                default_size: (None, root.cls_height)
