#:import constants misc.constants

<PlaybackMapSection>:  # SectionPanel
    pb_map: pb_map

    size_hint: (1, 1)
    title_text: "Плейбеки"
    PlaybackMap:
        id: pb_map

<PlaybackMap>:  # MapLayout
    cell_size: constants.MAP_LAYOUT_CELL_SIZE
    max_grid_size: constants.MAP_LAYOUT_MAX_GRID_SIZE
    grid_padding: constants.MAP_LAYOUT_GRID_PADDING
    grid_spacing: constants.MAP_LAYOUT_GRID_SPACING
