#:import constants misc.constants

<PlaybackEditorMapSection>:  # MenuPanel
    pb_map: pb_map

    size_hint: (1, 1)
    -width: 0

    playback: pb_map.playback

    PlaybackEditorMap:
        id: pb_map

<PlaybackEditorMap>:
    cell_size: constants.MAP_LAYOUT_CELL_SIZE
    max_grid_size: constants.MAP_LAYOUT_MAX_GRID_SIZE
    grid_padding: constants.MAP_LAYOUT_GRID_PADDING
    grid_spacing: constants.MAP_LAYOUT_GRID_SPACING
