<LabelInterpatchIndex>:  # RestrictedLabel
    size_hint: (0.27, 0.135)
    pos_hint: {"x": 0, "y": 0}
    font_size: "12sp"

<ButtonInterpatchUngroup>:  # HoverButton
    text: "U"
    size_hint: (0.27, 0.135)
    pos_hint: {"x": 0.73, "y": 0}
    font_size: "12sp"
    on_release: self.ungroup_interpatch()

<EditorPatchUi>:  # RelativeLayout
    playback: self.patch_map_editor.playback
    blocked: self.playback is None
