<-ImageButton>:
    state_image: self.background_down if self.is_down else self.background_normal
    canvas:
        Color:
            rgba: self.background_color
        Rectangle:
            size: self.size
            pos: self.pos
            source: self.state_image


<-ImageToggleButton>:
    state_image: self.background_down if self.is_down else self.background_normal
    canvas:
        Color:
            rgba: self.background_color
        Rectangle:
            size: self.size
            pos: self.pos
            source: self.state_image


<-HoverButton>:
    state_image: self.background_down if self.is_down else self.background_normal
    canvas:
        Color:
            rgba: self.background_color
        Rectangle:
            size: self.size
            pos: self.pos
            source: self.state_image
        Color:
            rgba: cs.Label.fg_disabled if self.disabled else cs.Label.fg
        Rectangle:
            texture: self.texture
            size: self.texture_size
            pos: int(self.center_x - self.texture_size[0] / 2.), int(self.center_y - self.texture_size[1] / 2.)


<-HoverToggleButton>:
    state_image: self.background_down if self.is_down else self.background_normal
    canvas:
        Color:
            rgba: self.background_color
        Rectangle:
            size: self.size
            pos: self.pos
            source: self.state_image
        Color:
            rgba: cs.Label.fg_disabled if self.disabled else cs.Label.fg
        Rectangle:
            texture: self.texture
            size: self.texture_size
            pos: int(self.center_x - self.texture_size[0] / 2.), int(self.center_y - self.texture_size[1] / 2.)


<OptionToggleButtonContextMenu>:
    scroll_layout: scroll_layout
    scrollview: scrollview

    size: ("150dp", "200dp")

    RestrictedLabel:
        text: root.title
        font_size: "14sp"
        size_hint: (1, None)
        size: self.texture_size
    ScrollLayout:
        id: scroll_layout
        scrollview: scrollview
        RecycleRestrictedScrollView:
            id: scrollview
            viewclass: root.option_cls
            scroll_by_content: True
            do_scroll_x: False
            do_scroll_by_element: True
            RecycleBoxLayout:
                size_hint: (1, None)
                orientation: "vertical"
                default_size_hint: (1, None)
                height: self.minimum_height
                default_size: (None, "30dp")



<-ImageOptionToggleButton>:
    state_image: self.background_down if self.pressed else self.background_normal
    canvas:
        Color:
            rgba: self.background_color
        Rectangle:
            size: self.size
            pos: self.pos
            source: self.state_image


<-OptionToggleButton>:
    state_image: self.background_down if self.pressed else self.background_normal
    canvas:
        Color:
            rgba: self.background_color
        Rectangle:
            size: self.size
            pos: self.pos
            source: self.state_image
        Color:
            rgba: cs.Label.fg_disabled if self.disabled else cs.Label.fg
        Rectangle:
            texture: self.texture
            size: self.texture_size
            pos: int(self.center_x - self.texture_size[0] / 2.), int(self.center_y - self.texture_size[1] / 2.)



<ColorToggleButton>:  # Widget
    canvas:
        Color:
            rgba: self.color
        Rectangle:
            size: self.size
            pos: self.pos
            source: self.source
        Color:
            rgba: self.border_color
        Line:
            rectangle: (self.x + 1, self.y + 1, self.width - 1, self.height - 1)
            width: 1


<ArrowBehavior>:
    canvas.after:
        Color:
            rgba: self.arrow_color if self.do_show_arrow else [0, 0, 0, 0]
        Triangle:
            points: self.arrow_points
