<DeviceListPanel>:  # SectionPanel
    box: box
    scrollview: scrollview
    title_text: root.title
    size_hint: (None, 1)
    ScrollLayout:
        size_hint: (None, 1)
        width: "175dp"
        scrollview: scrollview
        RestrictedScrollView:
            id: scrollview
            scroll_by_content: True
            canvas.before:
                Color:
                    rgba: root.bg_scrollview
                Rectangle:
                    pos: self.pos
                    size: self.size
            BoxLayout:
                id: box
                orientation: "vertical"
                size_hint: (1, None)
                height: self.minimum_height
