#:import cs misc.colorscheme
#:import uix_cs libs.uix.colorscheme
#:import imgs_path misc.imgs_path


<MDIWindow>:  # BoxLayout
    title_bar: title_bar
    title_bar_label: title_bar_label

    toggle_lock: toggle_lock.__self__
    toggle_expand: toggle_expand.__self__
    btn_close: btn_close.__self__

    size_hint: (None, None)
    size: ("600dp", "400dp")
    padding: "3dp"
    orientation: 'vertical'

    canvas.before:
        Color:
            rgba: uix_cs.general.menu_wrap_bg
        Rectangle:
            pos: self.pos
            size: self.size
        Color:
            rgba: self.border_color
        Line:
            width: dp(1)
            rectangle: (self.x + 1, self.y + 1, self.width - 1, self.height - 2)
    BoxLayout:
        id: title_bar
        size_hint: (1, None)
        height: "20dp"
        spacing: "4dp"
        RestrictedLabel:
            id: title_bar_label
            text: root.title
            size_hint_x: 1
            halign: 'left'
            valign: 'center'
            padding: ("6dp", 0)
            font_size: "12sp"
            text_size: self.size
            canvas.before:
                Color:
                    rgba: uix_cs.general.menu_bg
                Rectangle:
                    pos: self.pos
                    size: self.size
        ImageToggleButton:
            id: toggle_lock
            size_hint: (None, None)
            size: ("20dp", "20dp")
            is_down: root.locked
            on_is_down: root.locked = self.is_down
            -background_normal: imgs_path.mdi_lock_normal
            -background_down: imgs_path.mdi_lock_down
        ImageToggleButton:
            id: toggle_expand
            size_hint: (None, None)
            size: ("20dp", "20dp")
            is_down: root.expanded
            on_is_down: root.expanded = self.is_down
            -background_normal: imgs_path.mdi_expand_normal
            -background_down: imgs_path.mdi_expand_down
            disabled: toggle_lock.state == "down"
            discard_state_release: False
        ImageButton:
            id: btn_close
            size_hint: (None, None)
            size: ("20dp", "20dp")
            -background_normal: imgs_path.mdi_close_normal
            -background_down: imgs_path.mdi_close_down
            on_release: root.close()
