<ScrollBar>:  # BoxLayout
    layout_cursor: layout_cursor
    cursor: cursor

    size_hint: (None, 1) if self.orientation == "vertical" else (1, None)
    size: (self._default_width, self._default_height)
    canvas.before:
        Color:
            rgba: cs.general.menu_bg
        Rectangle:
            pos: self.pos
            size: self.size

    ArrowImageButton:
        reverse_arrow: True
        vertical_arrow: root.orientation == "vertical"
        arrow_size: ["10dp", "6dp"] if self.vertical_arrow else ["6dp", "10dp"]
        arrow_offset_right: "5dp" if self.vertical_arrow else "8dp"
        size_hint: (1, None) if root.orientation == "vertical" else (None, 1)
        height: root.width
        width: root.height
        on_press: root.on_press_btn_scroll(1)
        disabled: (root.scrollview._scroll_y <= 0.0) if root.orientation == "vertical" else (root.scrollview._scroll_x <= 0.0)

    RelativeLayout:
        id: layout_cursor
        ImageButton:
            id: cursor

    ArrowImageButton:
        vertical_arrow: root.orientation == "vertical"
        arrow_size: ["10dp", "6dp"] if self.vertical_arrow else ["6dp", "10dp"]
        arrow_offset_right: "5dp" if self.vertical_arrow else "6dp"
        size_hint: (1, None) if root.orientation == "vertical" else (None, 1)
        height: root.width
        width: root.height
        on_press: root.on_press_btn_scroll(-1)
        disabled: (root.scrollview._scroll_y >= 1.0) if root.orientation == "vertical" else (root.scrollview._scroll_x >= 1.0)


<ScrollLayout>:  # BoxLayout
    box_vertical: box_vertical

    orientation: "vertical"
    BoxLayout:
        id: box_vertical
