<MapSelector>:
    size_hint: (None, None)
    canvas:
        Color:
            rgba: cs.MapSelector.bg
        Rectangle:
            pos: self.pos
            size: self.size
        Color:
            rgba: cs.MapSelector.border
        Line:
            width: dp(1)
            rectangle: (self.x, self.y, self.width, self.height)


<SelectableBehavior>:
    size_hint: (None, None)
    canvas.after:
        Color:
            rgba: self.border_color
        Line:
            width: dp(1)
            rectangle: (self.x, self.y, self.width, self.height)


<MapLayout>:
    size_hint: (None, None)
    #size: (self.grid_size * constants.MAP_LAYOUT_MAX_SIZE, self.grid_size * constants.MAP_LAYOUT_MAX_SIZE)
    canvas:
        Color:
            rgba: cs.MapLayout.bg
        Rectangle:
            pos: self.pos
            size: self.size
        Color:
            rgba: cs.MapLayout.grid_color
        Line:
            points: root.grid_points
            width: 1


<MapScrollLayout>:
    size_hint: (1, 1)
    scroll_by_content: True
    scrollview: scrollview
    box: box
    RestrictedScrollView:
        id: scrollview
        size_hint: (1, 1)
        MapLayout:
            id: box
            scrollview: scrollview


<WorkspaceMapScrollLayout>:  # MapScrollLayout
    if_contain: False if self.box is None else len(self.box.children) > 0
