<Slider2D>:
    padding: 6
    size_hint: (1, 1)
    canvas:
        Color:
            rgba: (1, 1, 1, 1)
        Rectangle:
            size: self.size
            pos: self.pos
            source: imgs_path.slider_2d_bg
        Color:
            rgba: self.dot_color
        SmoothEllipse:
            pos: (self.dot_x, self.dot_y)
            size: (self.dot_radius, self.dot_radius)
        Color:
            rgba: self.line_color
        Line:
            width: dp(1)
            rectangle: (self.x + self.padding, self.y + self.padding, self.width - self.padding * 2, self.height - self.padding * 2)
        Line:
            width: dp(1)
            points: [self.x + self.padding, self.dot_y + self.dot_radius / 2, self.dot_x + self.dot_radius / 2, self.dot_y + self.dot_radius / 2, self.dot_x + self.dot_radius / 2, self.y + self.padding]
